version: "3.9"

services:
  db:
    image: postgres
    container_name: restrurant-postgres-db
    restart: always
    environment:
      POSTGRES_DB: restrurant_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres@123
    volumes:
      - postgres_prisma_data:/var/lib/postgresql/data
    ports:
      - 8008:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restrurant-app-nextjs
    restart: always
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@123@db:5432/restrurant_db
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules # Prevent reinstallation during development

volumes:
  postgres_prisma_data:
