version: "3.9"

services:
  db:
    image: postgres
    container_name: restrurant-postgres-db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_prisma_data:/var/lib/postgresql/data
    ports:
      - 8008:5432

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restrurant-app-nextjs
    restart: always
    ports:
      - 3001:3000
      - 5556:5555
    environment:
      DATABASE_URL: ${DATABASE_URL}
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  postgres_prisma_data:
